/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FileStorage } from "./FileStorage";

export { FileStorage__factory } from "./factories/FileStorage__factory";
